title: highway2vec
description: Representing OpenStreetMap microregions with respect to their road network characteristics
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one